# permissions for end users to edit autoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscaler-editor-role
rules:
- apiGroups:
  - devops.ysicing.me
  resources:
  - autoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.ysicing.me
  resources:
  - autoscalers/status
  verbs:
  - get
